// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chddomvncdbaotyhrate.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoZGRvbXZuY2RiYW90eWhyYXRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjQyODIsImV4cCI6MjA2MDEwMDI4Mn0.0bKtiwrTqSzBNWeZwMXnn8j_2O5-4WN4EaT47Ca5gPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);